import streamlit as st
import tensorflow as tf
from PIL import Image
import numpy as np

# 1. Page Configuration
st.set_page_config(page_title="AI vs Human Image Detector", page_icon="🔍")

# 2. Load the Model
@st.cache_resource
def load_my_model():
    # Ensure this filename matches your saved model from Colab
    return tf.keras.models.load_model('ai_human_detector_v2.h5')

model = load_my_model()

# 3. App Header & Styling
st.title("🔍 AI vs Human Image Detector")
st.markdown("""
Upload any image to see if it was generated by an **AI** or taken by a **Human**.
*Model trained on the CIFAKE dataset (100,000 images).*
""")

# 4. Image Upload Logic
uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Display the uploaded image
    img = Image.open(uploaded_file)
    st.image(img, caption="Uploaded Image", use_container_width=True)
    
    # 5. Preprocessing
    # Resizing to 32x32 as required by the CIFAKE model architecture
    img_resized = img.resize((32, 32))
    img_array = tf.keras.preprocessing.image.img_to_array(img_resized)
    img_array = np.expand_dims(img_array, axis=0) 
    # Note: No division by 255 here because the model includes a Rescaling layer

    # 6. Prediction
    if st.button("Run Detection"):
        with st.spinner('Analyzing pixel patterns...'):
            prediction = model.predict(img_array)[0][0]
            
            # --- FIXED LOGIC ---
            # Class 0 (Alphabetical: FAKE) = AI Generated
            # Class 1 (Alphabetical: REAL) = Human Photograph
            
            if prediction < 0.5:
                # Calculate AI confidence (How close to 0 it is)
                confidence = (1 - prediction) 
                st.error(f"### Result: AI GENERATED")
                st.write(f"Confidence Score: **{confidence * 100:.2f}%**")
                # Progress bar shows how sure it is that it's AI
                st.progress(float(confidence))
            else:
                # Calculate Human confidence (How close to 1 it is)
                confidence = prediction 
                st.success(f"### Result: HUMAN PHOTOGRAPH")
                st.write(f"Confidence Score: **{confidence * 100:.2f}%**")
                # Progress bar shows how sure it is that it's Human
                st.progress(float(confidence))

# Footer
st.divider()
st.caption("Developed for BCA Final Year Project - 2026")